/* GENERATED by tools/gen_web_config.py from main/panel_config.h and main/themes.h.
 * Do not edit by hand: change the headers and re-run the script. */
window.PANEL_CONFIG = {
  "weather": "weather.buienradar",
  "tabs": [
    {
      "name": "Beneden",
      "lights": [
        {
          "id": "light.lampen_beneden_verdieping",
          "label": "Beneden"
        }
      ],
      "scenes": [
        {
          "id": "scene.woonkamer_alles_aan",
          "label": "Alles aan"
        },
        {
          "id": "scene.woonkamer_avond",
          "label": "Avond sfeer"
        },
        {
          "id": "scene.woonkamer_avond_licht",
          "label": "Avond licht"
        },
        {
          "id": "scene.woonkamer_paars_rood",
          "label": "Paars rood"
        },
        {
          "id": "scene.woonkamer_alles_uit",
          "label": "Alles uit"
        },
        {
          "id": "scene.woonkamer_cuba",
          "label": "Cuba"
        },
        {
          "id": "scene.woonkamer_min",
          "label": "Min"
        },
        {
          "id": "scene.woonkamer_max",
          "label": "Max"
        }
      ],
      "devices": [
        {
          "id": "light.lamp_woonkamer_kubus_1",
          "label": "Kubus"
        },
        {
          "id": "light.lamp_valerie_rieten_1",
          "label": "Rieten"
        },
        {
          "id": "light.lamp_woonkamer_plafond_tv_2",
          "label": "Plafond TV 2"
        },
        {
          "id": "light.lamp_woonkamer_plafond_tv_3",
          "label": "Plafond TV 3"
        },
        {
          "id": "light.lamp_grond_1",
          "label": "Grond"
        },
        {
          "id": "light.lamp_keuken_eettafel_1",
          "label": "Eettafel"
        },
        {
          "id": "light.lamp_keuken_plafond_1",
          "label": "Keuken plafond"
        },
        {
          "id": "light.lamp_keuken_muur_1",
          "label": "Keuken muur 1"
        },
        {
          "id": "light.lamp_keuken_muur_2",
          "label": "Keuken muur 2"
        },
        {
          "id": "light.lamp_keuken_muur_3",
          "label": "Keuken muur 3"
        },
        {
          "id": "light.lamp_zitkamer_1",
          "label": "Zitkamer"
        },
        {
          "id": "light.lamp_zitkamer_achter_1",
          "label": "Zitk. achter 1"
        },
        {
          "id": "light.lamp_zitkamer_achter_2",
          "label": "Zitk. achter 2"
        },
        {
          "id": "light.lamp_zitkamer_achter_3",
          "label": "Zitk. achter 3"
        },
        {
          "id": "light.lamp_zitkamer_achter_muur_1",
          "label": "Zitk. muur 1"
        },
        {
          "id": "light.lamp_zitkamer_achter_muur_2",
          "label": "Zitk. muur 2"
        },
        {
          "id": "light.lamp_playroom_1",
          "label": "Gameroom"
        },
        {
          "id": "light.lamp_playroom_muur_1",
          "label": "Gameroom muur 1"
        },
        {
          "id": "light.lamp_playroom_muur_2",
          "label": "Gameroom muur 2"
        },
        {
          "id": "light.lamp_playroom_muur_3",
          "label": "Gameroom muur 3"
        },
        {
          "id": "light.lamp_gang_deur_1",
          "label": "Gang deur"
        },
        {
          "id": "light.lamp_gang_trap_beneden_1",
          "label": "Gang trap"
        },
        {
          "id": "light.lamp_wc_beneden_1",
          "label": "WC"
        },
        {
          "id": "light.lamp_buiten_1",
          "label": "Buiten"
        }
      ],
      "icons": [
        "bolt",
        "eye-off",
        "eye",
        "drop",
        "power",
        null,
        "minus",
        "plus"
      ],
      "swatches": [
        null,
        null,
        null,
        null,
        null,
        {
          "a": "#1fb8a6",
          "b": "#ffc857"
        },
        null,
        null
      ],
      "sceneTiles": true,
      "areas": [
        {
          "label": "Keuken",
          "lights": [
            "light.lamp_keuken_plafond_1",
            "light.lamp_keuken_plafond_2",
            "light.lamp_keuken_plafond_3",
            "light.lamp_keuken_plafond_4",
            "light.lamp_keuken_plafond_5",
            "light.lamp_keuken_plafond_6",
            "light.lamp_keuken_plafond_7",
            "light.lamp_keuken_muur_1",
            "light.lamp_keuken_muur_2",
            "light.lamp_keuken_muur_3"
          ]
        },
        {
          "label": "Eetkamer",
          "lights": [
            "light.lamp_keuken_eettafel_1"
          ]
        },
        {
          "label": "Zitkamer",
          "lights": [
            "light.lamp_zitkamer_voor_1",
            "light.lamp_zitkamer_voor_2",
            "light.lamp_zitkamer_1",
            "light.lamp_grond_1",
            "light.lamp_woonkamer_kubus_1",
            "light.lamp_valerie_rieten_1"
          ]
        },
        {
          "label": "Zitk. achter",
          "lights": [
            "light.lamp_zitkamer_achter_1",
            "light.lamp_zitkamer_achter_2",
            "light.lamp_zitkamer_achter_3",
            "light.lamp_zitkamer_achter_muur_1",
            "light.lamp_zitkamer_achter_muur_2"
          ]
        },
        {
          "label": "Gameroom",
          "lights": [
            "light.lamp_playroom_1",
            "light.lamp_playroom_led_1",
            "light.lamp_playroom_muur_1",
            "light.lamp_playroom_muur_2",
            "light.lamp_playroom_muur_3"
          ]
        },
        {
          "label": "Gang",
          "lights": [
            "light.lamp_gang_plafond_1",
            "light.lamp_gang_plafond_2",
            "light.lamp_gang_plafond_3",
            "light.lamp_gang_deur_1",
            "light.lamp_gang_trap_beneden_1",
            "light.lamp_wc_beneden_1"
          ]
        },
        {
          "label": "Buiten",
          "lights": [
            "light.lamp_buiten_1"
          ]
        }
      ]
    },
    {
      "name": "Boven",
      "lights": [
        {
          "id": "light.lamp_slaapkamer_gillis_ilse",
          "label": "Slaapkamer"
        },
        {
          "id": "light.lamp_valerie_kamer_1",
          "label": "Valerie"
        },
        {
          "id": "light.lamp_jongens_kamer_1",
          "label": "Jongens"
        },
        {
          "id": "light.lamp_badkamer_2_plafond_2",
          "label": "Badkamer 2"
        },
        {
          "id": "light.lamp_badkamer_2_plafond_3",
          "label": "Badkamer 3"
        }
      ],
      "scenes": [
        {
          "id": "scene.slaapkamer_aan",
          "label": "Slaapk. aan"
        },
        {
          "id": "scene.slaapkamer_aan_fel",
          "label": "Slaapk. fel"
        },
        {
          "id": "scene.slaapkamer_uit",
          "label": "Slaapk. uit"
        }
      ],
      "devices": [
        {
          "id": "light.lamp_slaapkamer_gillis_ilse",
          "label": "Slaapkamer"
        },
        {
          "id": "light.lamp_slaapkamer_staand_ilse_gillis",
          "label": "Slaapk. staand"
        },
        {
          "id": "light.lamp_gillis_ilse_nachtkasje_lamp_gillis_ilse_nachtkasje",
          "label": "Nachtkastje"
        },
        {
          "id": "light.lamp_valerie_kamer_1",
          "label": "Valerie"
        },
        {
          "id": "light.lamp_jongens_kamer_1",
          "label": "Jongens"
        },
        {
          "id": "light.lamp_badkamer_2_plafond_1",
          "label": "Badkamer 1"
        },
        {
          "id": "light.lamp_badkamer_2_plafond_2",
          "label": "Badkamer 2"
        },
        {
          "id": "light.lamp_badkamer_2_plafond_3",
          "label": "Badkamer 3"
        }
      ],
      "icons": null,
      "swatches": null,
      "sceneTiles": false,
      "areas": [
        {
          "label": "Slaapkamer",
          "lights": [
            "light.lamp_slaapkamer_gillis_ilse",
            "light.lamp_slaapkamer_staand_ilse_gillis",
            "light.lamp_gillis_ilse_nachtkasje_lamp_gillis_ilse_nachtkasje",
            "light.lamp_slaapkamer_achter_1",
            "light.lamp_slaapkamer_achter_nachtkast_1",
            "light.lamp_slaapkamer_plafond_achter_1"
          ]
        },
        {
          "label": "Valerie",
          "lights": [
            "light.lamp_valerie_kamer_1"
          ]
        },
        {
          "label": "Jongens",
          "lights": [
            "light.lamp_jongens_kamer_1"
          ]
        },
        {
          "label": "Badkamer",
          "lights": [
            "light.lamp_badkamer_2_plafond_1",
            "light.lamp_badkamer_2_plafond_2",
            "light.lamp_badkamer_2_plafond_3",
            "light.lamp_badkamer_3",
            "light.lamp_badkamer_muur_1",
            "light.lamp_badkamer_muur_2",
            "light.lamp_badkamer_spiegel_1"
          ]
        },
        {
          "label": "Gang",
          "lights": [
            "light.lamp_gang_boven_plafond_1",
            "light.lamp_gang_boven_plafond_2",
            "light.lamp_gang_boven_plafond_3",
            "light.lamp_gang_boven_plafond_4"
          ]
        },
        {
          "label": "Kledingkast",
          "lights": [
            "light.lamp_kledingkast_plafond_1",
            "light.lamp_kledingkast_plafond_2"
          ]
        }
      ]
    },
    {
      "name": "Zolder",
      "lights": [
        {
          "id": "light.lamp_zolder_gang",
          "label": "Gang"
        },
        {
          "id": "light.lamp_zolder_baby_kamer_1",
          "label": "Baby 1"
        },
        {
          "id": "light.lamp_zolder_baby_kamer_2",
          "label": "Baby 2"
        }
      ],
      "scenes": [],
      "devices": [
        {
          "id": "light.lamp_zolder_gang",
          "label": "Gang"
        },
        {
          "id": "light.lamp_zolder_baby_kamer_1",
          "label": "Baby 1"
        },
        {
          "id": "light.lamp_zolder_baby_kamer_2",
          "label": "Baby 2"
        }
      ],
      "icons": null,
      "swatches": null,
      "sceneTiles": false,
      "areas": [
        {
          "label": "Gang",
          "lights": [
            "light.lamp_zolder_gang",
            "light.lamp_zolder_tussengang_1"
          ]
        },
        {
          "label": "Babykamer",
          "lights": [
            "light.lamp_zolder_baby_kamer_1",
            "light.lamp_zolder_baby_kamer_2"
          ]
        },
        {
          "label": "Voorkamer",
          "lights": [
            "light.lamp_zolder_voorkamer_1"
          ]
        },
        {
          "label": "Achterkamer",
          "lights": [
            "light.lamp_zolder_achterkamer_1"
          ]
        }
      ]
    },
    {
      "name": "Garage",
      "lights": [
        {
          "id": "light.lampen_garage",
          "label": "Garage"
        }
      ],
      "scenes": [
        {
          "id": "scene.garage_fel",
          "label": "Fel"
        },
        {
          "id": "scene.garage_half",
          "label": "Half"
        },
        {
          "id": "scene.garage_gedimd",
          "label": "Gedimd"
        },
        {
          "id": "scene.garage_warm",
          "label": "Warm"
        },
        {
          "id": "scene.garage_oranje",
          "label": "Oranje"
        },
        {
          "id": "scene.garage_rood",
          "label": "Rood"
        },
        {
          "id": "scene.garage_blauw",
          "label": "Blauw"
        },
        {
          "id": "scene.garage_rood_blauw",
          "label": "Rood blauw"
        },
        {
          "id": "scene.garage_pink_paars_groen",
          "label": "Roze paars"
        },
        {
          "id": "scene.garage_cuba",
          "label": "Cuba"
        },
        {
          "id": "scene.garage_regenboog",
          "label": "Regenboog"
        }
      ],
      "devices": [
        {
          "id": "light.lamp_garage_1",
          "label": "Lamp 1"
        },
        {
          "id": "light.lamp_garage_2",
          "label": "Lamp 2"
        },
        {
          "id": "light.lamp_garage_3",
          "label": "Lamp 3"
        },
        {
          "id": "light.lamp_garage_5",
          "label": "Lamp 5"
        },
        {
          "id": "light.lamp_garage_6",
          "label": "Lamp 6"
        },
        {
          "id": "light.lamp_garage_7",
          "label": "Lamp 7"
        },
        {
          "id": "light.lamp_garage_8",
          "label": "Lamp 8"
        },
        {
          "id": "light.lamp_garage_9",
          "label": "Lamp 9"
        },
        {
          "id": "light.lamp_garage_11",
          "label": "Lamp 11"
        },
        {
          "id": "light.lamp_garage_12",
          "label": "Lamp 12"
        },
        {
          "id": "light.lamp_garage_13",
          "label": "Lamp 13"
        },
        {
          "id": "light.lamp_garage_14",
          "label": "Lamp 14"
        },
        {
          "id": "light.lamp_garage_15",
          "label": "Lamp 15"
        },
        {
          "id": "light.lamp_garage_16",
          "label": "Lamp 16"
        },
        {
          "id": "light.lamp_garage_17",
          "label": "Lamp 17"
        },
        {
          "id": "light.lamp_garage_18",
          "label": "Lamp 18"
        },
        {
          "id": "light.lamp_garage_19",
          "label": "Lamp 19"
        },
        {
          "id": "light.lamp_garage_20",
          "label": "Lamp 20"
        },
        {
          "id": "light.lamp_garage_21",
          "label": "Lamp 21"
        }
      ],
      "icons": null,
      "swatches": [
        {
          "a": "#ffffff",
          "b": null
        },
        {
          "a": "#aeb3bd",
          "b": null
        },
        {
          "a": "#5a5f6a",
          "b": null
        },
        {
          "a": "#ffb46b",
          "b": null
        },
        {
          "a": "#ff8a1f",
          "b": null
        },
        {
          "a": "#e0323c",
          "b": null
        },
        {
          "a": "#3b6cff",
          "b": null
        },
        {
          "a": "#e0323c",
          "b": "#3b6cff"
        },
        {
          "a": "#ff5fb4",
          "b": "#39d98a"
        },
        {
          "a": "#1fb8a6",
          "b": "#ffc857"
        },
        {
          "a": "rainbow",
          "b": null
        }
      ],
      "sceneTiles": true,
      "areas": []
    }
  ],
  "floors": [
    {
      "tab": 0,
      "label": "0",
      "name": "Begane grond"
    },
    {
      "tab": 1,
      "label": "1",
      "name": "1e verdieping"
    },
    {
      "tab": 2,
      "label": "2",
      "name": "Zolder"
    }
  ],
  "sections": [
    {
      "name": "Verlichting",
      "kind": "floors",
      "tab": null
    },
    {
      "name": "Apparaten",
      "kind": "appliances",
      "tab": null
    },
    {
      "name": "Schoonmaak",
      "kind": "vacuum",
      "tab": null
    },
    {
      "name": "Garage",
      "kind": "tab",
      "tab": 3
    },
    {
      "name": "Tesla",
      "kind": "car",
      "tab": null
    }
  ],
  "sensors": [
    {
      "temp": "sensor.sensor_buiten_voor_1_temperature",
      "humidity": "sensor.sensor_buiten_voor_1_humidity",
      "label": "Buiten",
      "abbr": "BUI",
      "indoor": false
    },
    {
      "temp": "sensor.sensor_voorkamer_1_temperature",
      "humidity": "sensor.sensor_voorkamer_1_humidity",
      "label": "Zitkamer",
      "abbr": "ZIT",
      "indoor": true
    },
    {
      "temp": "sensor.sensor_keuken_1_temperature",
      "humidity": "sensor.sensor_keuken_1_humidity",
      "label": "Keuken",
      "abbr": "KEU",
      "indoor": true
    },
    {
      "temp": "sensor.sensor_zitkamer_achter_1_temperature",
      "humidity": "sensor.sensor_zitkamer_achter_1_humidity",
      "label": "Gameroom",
      "abbr": "GAM",
      "indoor": true
    },
    {
      "temp": "sensor.sensor_zolder_1_temperature",
      "humidity": "sensor.sensor_zolder_1_humidity",
      "label": "Zolder",
      "abbr": "ZOL",
      "indoor": true
    }
  ],
  "air": [
    {
      "label": "Luchtkwaliteit keuken",
      "short": "Lucht keuken",
      "abbr": "CO2",
      "co2": "sensor.luchtkwaliteit_keuken_carbon_dioxide",
      "pm25": "sensor.luchtkwaliteit_keuken_pm2_5",
      "quality": "sensor.luchtkwaliteit_keuken_air_quality",
      "temp": "sensor.luchtkwaliteit_keuken_temperature",
      "humidity": "sensor.luchtkwaliteit_keuken_humidity"
    }
  ],
  "airBands": {
    "co2Good": 800.0,
    "co2Poor": 1200.0,
    "co2MinValid": 250.0,
    "pm25Good": 15.0,
    "pm25Poor": 35.0
  },
  "vacuum": {
    "label": "Stofzuiger",
    "vacuum": "vacuum.stofzuiger_xiaomi_robot_cleaner",
    "status": "sensor.stofzuiger_xiaomi_status",
    "battery": "sensor.stofzuiger_xiaomi_battery_level",
    "area": "sensor.stofzuiger_xiaomi_clean_area",
    "mode": "select.stofzuiger_xiaomi_clean_mode",
    "fan": "select.stofzuiger_xiaomi_fan_mode",
    "water": "select.stofzuiger_xiaomi_water_mode",
    "locate": "button.stofzuiger_xiaomi_seek_robot",
    "roomsDomain": "robotkamers",
    "rooms": [
      {
        "id": 5,
        "label": "Keuken"
      },
      {
        "id": 8,
        "label": "Eetkamer"
      },
      {
        "id": 3,
        "label": "Zitkamer achter"
      },
      {
        "id": 7,
        "label": "Gameroom"
      },
      {
        "id": 9,
        "label": "Gang"
      },
      {
        "id": 4,
        "label": "Garage"
      }
    ]
  },
  "bike": {
    "label": "Fiets",
    "battery": "sensor.st7_battery",
    "location": "device_tracker.st7_location",
    "lock": "binary_sensor.st7_bike_lock",
    "speed": "sensor.st7_bike_speed"
  },
  "car": {
    "label": "Tesla",
    "name": "vlm",
    "entities": {
      "battery": "sensor.vlm_battery_level",
      "usable": "sensor.vlm_usable_battery_level",
      "range": "sensor.vlm_battery_range",
      "estRange": "sensor.vlm_estimate_battery_range",
      "charging": "sensor.vlm_charging",
      "charge": "switch.vlm_charge",
      "chargeLimit": "number.vlm_charge_limit",
      "chargeAmps": "number.vlm_charge_current",
      "chargerPower": "sensor.vlm_charger_power",
      "chargerVoltage": "sensor.vlm_charger_voltage",
      "chargerCurrent": "sensor.vlm_charger_current",
      "chargeRate": "sensor.vlm_charge_rate",
      "energyAdded": "sensor.vlm_charge_energy_added",
      "timeToFull": "sensor.vlm_time_to_full_charge",
      "cable": "binary_sensor.vlm_charge_cable",
      "port": "cover.vlm_charge_port_door",
      "cableLock": "lock.vlm_charge_cable_lock",
      "lock": "lock.vlm_lock",
      "sentry": "switch.vlm_sentry_mode",
      "frunk": "cover.vlm_frunk",
      "trunk": "cover.vlm_trunk",
      "windows": "cover.vlm_windows",
      "doorFL": "binary_sensor.vlm_front_driver_door",
      "doorFR": "binary_sensor.vlm_front_passenger_door",
      "doorRL": "binary_sensor.vlm_rear_driver_door",
      "doorRR": "binary_sensor.vlm_rear_passenger_door",
      "winFL": "binary_sensor.vlm_front_driver_window",
      "winFR": "binary_sensor.vlm_front_passenger_window",
      "winRL": "binary_sensor.vlm_rear_driver_window",
      "winRR": "binary_sensor.vlm_rear_passenger_window",
      "climate": "climate.vlm_climate",
      "inside": "sensor.vlm_inside_temperature",
      "outside": "sensor.vlm_outside_temperature",
      "defrost": "switch.vlm_defrost",
      "seatFL": "select.vlm_seat_heater_front_left",
      "seatFR": "select.vlm_seat_heater_front_right",
      "seatRL": "select.vlm_seat_heater_rear_left",
      "seatRC": "select.vlm_seat_heater_rear_center",
      "seatRR": "select.vlm_seat_heater_rear_right",
      "wheel": "select.vlm_steering_wheel_heater",
      "precond": "binary_sensor.vlm_preconditioning",
      "battHeater": "binary_sensor.vlm_battery_heater",
      "online": "binary_sensor.vlm_status",
      "present": "binary_sensor.vlm_user_present",
      "location": "device_tracker.vlm_location",
      "shift": "sensor.vlm_shift_state",
      "speed": "sensor.vlm_speed",
      "power": "sensor.vlm_power",
      "odometer": "sensor.vlm_odometer",
      "tireFL": "sensor.vlm_tire_pressure_front_left",
      "tireFR": "sensor.vlm_tire_pressure_front_right",
      "tireRL": "sensor.vlm_tire_pressure_rear_left",
      "tireRR": "sensor.vlm_tire_pressure_rear_right",
      "tireWarnFL": "binary_sensor.vlm_tire_pressure_warning_front_left",
      "tireWarnFR": "binary_sensor.vlm_tire_pressure_warning_front_right",
      "tireWarnRL": "binary_sensor.vlm_tire_pressure_warning_rear_left",
      "tireWarnRR": "binary_sensor.vlm_tire_pressure_warning_rear_right",
      "destination": "sensor.vlm_destination",
      "distToArrival": "sensor.vlm_distance_to_arrival",
      "timeToArrival": "sensor.vlm_time_to_arrival",
      "socAtArrival": "sensor.vlm_state_of_charge_at_arrival",
      "trafficDelay": "sensor.vlm_traffic_delay",
      "flash": "button.vlm_flash_lights",
      "honk": "button.vlm_honk_horn",
      "homelink": "button.vlm_homelink",
      "keyless": "button.vlm_keyless_driving",
      "fart": "button.vlm_play_fart",
      "wake": "button.vlm_wake",
      "media": "media_player.vlm_media_player",
      "update": "update.vlm_update"
    },
    "battery": "sensor.vlm_battery_level",
    "range": "sensor.vlm_battery_range",
    "charging": "sensor.vlm_charging",
    "lock": "lock.vlm_lock"
  },
  "appliances": [
    {
      "kind": "washer",
      "label": "Wasmachine",
      "name": "wasruimte_wasmachine",
      "entities": {
        "state": "select.wasruimte_wasmachine",
        "machine": "sensor.wasruimte_wasmachine_machine_state",
        "job": "sensor.wasruimte_wasmachine_job_state",
        "done": "sensor.wasruimte_wasmachine_completion_time",
        "power": "sensor.wasruimte_wasmachine_power",
        "energy": "sensor.wasruimte_wasmachine_energy",
        "remote": "binary_sensor.wasruimte_wasmachine_remote_control",
        "lock": "binary_sensor.wasruimte_wasmachine_child_lock",
        "on": "binary_sensor.wasruimte_wasmachine_power",
        "water": "sensor.wasruimte_wasmachine_water_consumption"
      }
    },
    {
      "kind": "dryer",
      "label": "Droger",
      "name": "wasruimte_droger",
      "entities": {
        "state": "select.wasruimte_droger",
        "machine": "sensor.wasruimte_droger_machine_state",
        "job": "sensor.wasruimte_droger_job_state",
        "done": "sensor.wasruimte_droger_completion_time",
        "power": "sensor.wasruimte_droger_power",
        "energy": "sensor.wasruimte_droger_energy",
        "remote": "binary_sensor.wasruimte_droger_remote_control",
        "lock": "binary_sensor.wasruimte_droger_child_lock",
        "on": "binary_sensor.wasruimte_droger_power"
      }
    },
    {
      "kind": "dishwasher",
      "label": "Vaatwasser",
      "name": "dishwasher",
      "entities": {
        "op": "sensor.dishwasher_bsh_common_status_operationstate",
        "door": "sensor.dishwasher_bsh_common_status_doorstate",
        "phase": "sensor.dishwasher_dishcare_dishwasher_status_programphase",
        "selected": "select.dishwasher_bsh_common_root_selectedprogram",
        "active": "select.dishwasher_bsh_common_root_activeprogram",
        "remaining": "sensor.dishwasher_bsh_common_option_remainingprogramtime",
        "progress": "sensor.dishwasher_bsh_common_option_programprogress",
        "startAllowed": "binary_sensor.dishwasher_bsh_common_status_remotecontrolstartallowed",
        "abort": "button.dishwasher_bsh_common_command_abortprogram",
        "energy": "sensor.dishwasher_bsh_common_option_energyforecast",
        "water": "sensor.dishwasher_bsh_common_option_waterforecast",
        "care": "sensor.dishwasher_dishcare_dishwasher_status_machinecarereminder_remainingprogramruns",
        "extradry": "switch.dishwasher_dishcare_dishwasher_setting_extradry",
        "hygiene": "switch.dishwasher_dishcare_dishwasher_option_hygieneplus",
        "speed": "switch.dishwasher_dishcare_dishwasher_option_variospeedplus",
        "silence": "switch.dishwasher_dishcare_dishwasher_option_silenceondemand"
      }
    },
    {
      "kind": "oven",
      "label": "Oven",
      "name": "oven",
      "entities": {
        "op": "sensor.oven_bsh_common_status_operationstate",
        "door": "sensor.oven_bsh_common_status_doorstate",
        "temp": "sensor.oven_cooking_oven_status_cavity_001_currenttemperature",
        "setpoint": "sensor.oven_cooking_oven_status_cavity_001_setpointtemperature",
        "program": "sensor.oven_bsh_common_option_programname",
        "remaining": "sensor.oven_bsh_common_option_remainingprogramtime",
        "elapsed": "sensor.oven_bsh_common_option_elapsedprogramtime",
        "progress": "sensor.oven_bsh_common_option_programprogress",
        "pause": "button.oven_bsh_common_command_pauseprogram",
        "resume": "button.oven_bsh_common_command_resumeprogram",
        "abort": "button.oven_bsh_common_command_abortprogram",
        "childlock": "switch.oven_bsh_common_setting_childlock",
        "light": "binary_sensor.oven_bsh_common_status_interiorilluminationactive"
      }
    },
    {
      "kind": "filter",
      "label": "Filter",
      "name": "atag_plasmafilter",
      "entities": {
        "active": "binary_sensor.atag_plasmafilter_statisch_4_kv_filter",
        "mode": "sensor.atag_plasmafilter_modus",
        "airflow": "sensor.atag_plasmafilter_luchtstroom",
        "cell1": "sensor.atag_plasmafilter_looptijd_plasmacel_1",
        "cell2": "sensor.atag_plasmafilter_looptijd_plasmacel_2",
        "voltage": "sensor.atag_plasmafilter_spanning",
        "current": "sensor.atag_plasmafilter_stroom"
      }
    },
    {
      "kind": "hob",
      "label": "Kookplaat",
      "name": "hob",
      "entities": {
        "op": "sensor.hob_bsh_common_status_operationstate",
        "power": "sensor.hob_bsh_common_setting_powerstate",
        "zone1": "sensor.hob_cooking_hob_status_zone_100_powerlevel",
        "zone2": "sensor.hob_cooking_hob_status_zone_200_powerlevel",
        "zone3": "sensor.hob_cooking_hob_status_zone_300_powerlevel",
        "zone4": "sensor.hob_cooking_hob_status_zone_400_powerlevel",
        "childlock": "binary_sensor.hob_bsh_common_setting_childlock",
        "filter": "sensor.hob_cooking_hob_status_carbonfiltersaturation",
        "filterReset": "button.hob_cooking_hob_command_carbonfilterreset",
        "vent": "select.hob_cooking_hob_setting_ventilation",
        "airmode": "select.hob_cooking_hob_setting_aircirculationmode"
      }
    },
    {
      "kind": "fridge",
      "label": "Koelkast",
      "name": "koelkast_1",
      "entities": {
        "temp": "sensor.koelkast_1",
        "setpoint": "number.koelkast_1_setpoint",
        "supercool": "switch.koelkast_1_supercool",
        "party": "switch.koelkast_1_partymode",
        "night": "switch.koelkast_1_nightmode"
      }
    }
  ],
  "media": [
    {
      "id": "media_player.living_room",
      "label": "Woonkamer"
    },
    {
      "id": "media_player.kitchen",
      "label": "Keuken"
    },
    {
      "id": "media_player.media_room",
      "label": "Media room"
    }
  ],
  "comfort": {
    "tempMin": 19.0,
    "tempMax": 24.0,
    "tempHot": 26.0,
    "humMin": 40.0,
    "humMax": 60.0,
    "humMargin": 10.0
  },
  "themes": [
    {
      "name": "Nacht",
      "bg": "#111318",
      "toolbar": "#0c0e12",
      "tile": "#232833",
      "tile_off": "#1a1d24",
      "tile_on": "#ffb84d",
      "on_text": "#241a05",
      "on_sub": "#6b5518",
      "text": "#eef0f5",
      "text_dim": "#848b9c",
      "text_soft": "#c6cbd6",
      "scene": "#2b3444",
      "scene_on": "#a78bfa",
      "scene_text": "#1a1030",
      "scene_sub": "#3b2d66",
      "accent": "#ffb84d",
      "grid": "#2b3140"
    },
    {
      "name": "Middernacht",
      "bg": "#000000",
      "toolbar": "#000000",
      "tile": "#15181d",
      "tile_off": "#0b0d10",
      "tile_on": "#3ee0d8",
      "on_text": "#03211f",
      "on_sub": "#0e5c58",
      "text": "#f2f4f8",
      "text_dim": "#7d8494",
      "text_soft": "#b9bfcc",
      "scene": "#1c2027",
      "scene_on": "#5ad1ff",
      "scene_text": "#06202c",
      "scene_sub": "#0f4b66",
      "accent": "#3ee0d8",
      "grid": "#22262d"
    },
    {
      "name": "Warm",
      "bg": "#1a1412",
      "toolbar": "#120d0b",
      "tile": "#2e2420",
      "tile_off": "#221a17",
      "tile_on": "#ff8c42",
      "on_text": "#2b1200",
      "on_sub": "#7a3f1a",
      "text": "#f6ede6",
      "text_dim": "#9c8b82",
      "text_soft": "#d3c4ba",
      "scene": "#3a2c27",
      "scene_on": "#e8a27a",
      "scene_text": "#2b1a12",
      "scene_sub": "#6b3d2a",
      "accent": "#ff8c42",
      "grid": "#3a2e29"
    },
    {
      "name": "Licht",
      "bg": "#f3f4f7",
      "toolbar": "#ffffff",
      "tile": "#ffffff",
      "tile_off": "#e6e8ee",
      "tile_on": "#ffb84d",
      "on_text": "#241a05",
      "on_sub": "#6b5518",
      "text": "#1c2230",
      "text_dim": "#6b7280",
      "text_soft": "#4b5563",
      "scene": "#e4e7ee",
      "scene_on": "#8b5cf6",
      "scene_text": "#ffffff",
      "scene_sub": "#ede9fe",
      "accent": "#d97706",
      "grid": "#d9dce3"
    },
    {
      "name": "Bos",
      "bg": "#0f1a14",
      "toolbar": "#0a120e",
      "tile": "#1d2e24",
      "tile_off": "#16241c",
      "tile_on": "#a3e635",
      "on_text": "#14260a",
      "on_sub": "#4d6d1a",
      "text": "#eaf3ec",
      "text_dim": "#86a08f",
      "text_soft": "#c2d3c6",
      "scene": "#25392d",
      "scene_on": "#6ee7b7",
      "scene_text": "#06301f",
      "scene_sub": "#1f5a41",
      "accent": "#a3e635",
      "grid": "#243a2e"
    },
    {
      "name": "Oceaan",
      "bg": "#0b1626",
      "toolbar": "#070f1b",
      "tile": "#162a44",
      "tile_off": "#102036",
      "tile_on": "#38bdf8",
      "on_text": "#06263a",
      "on_sub": "#0b4a66",
      "text": "#e6f0fb",
      "text_dim": "#7f95b0",
      "text_soft": "#bccbe0",
      "scene": "#1d3556",
      "scene_on": "#fbbf24",
      "scene_text": "#3a2a05",
      "scene_sub": "#5c4408",
      "accent": "#38bdf8",
      "grid": "#1c3352"
    }
  ]
};
